{"uuid": "d6a6a5d2-c236-4a16-9f0a-aa76acac20bf", "children": ["8922a96f-e012-4077-9c99-7f5e56b82470", "b2515bef-430e-46ca-9429-ee23a9a80aea"], "befores": [{"name": "test_setup", "status": "passed", "start": 1570691357871, "stop": 1570691369640}], "afters": [{"name": "test_setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=77.0.3865.90)\n\n", "trace": "  File \"C:\\Users\\FRESCANO143\\AppData\\Roaming\\Python\\Python37\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\FRESCANO143\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 787, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\FRESCANO143\\NextoryFramework\\conftest.py\", line 23, in test_setup\n    driver.close()\n  File \"C:\\Users\\FRESCANO143\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\Users\\FRESCANO143\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\FRESCANO143\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1570691380892, "stop": 1570691381664}], "start": 1570691357871, "stop": 1570691381664}